<?php

use kartik\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;

$helper = new backend\controllers\Helper();
$this->registerJs($this->render('checkbox.js'), 5);
/* @var $this yii\web\View */
/* @var $searchModel backend\models\MembersSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', '');
//$this->params['breadcrumbs'][] = $this->title;
?>

<form>
    <input type="hidden" value="<?= $counterData['id'] ?>" id="clickedCounter">
</form>
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header p-2">
            <ul class="nav nav-pills">
                <li class="nav-item"><a class="nav-link active" href="#additionalinfo" data-toggle="tab">MEMBERSHIP SEARCH</a></li>
                <!--<li class="nav-item"><a class="nav-link" href="#points" data-toggle="tab">Points</a></li>-->
                <li class="nav-item"><a class="nav-link" href="#counterReport" data-toggle="tab">MY TRANSACTION</a></li>
                <!--<li class="nav-item"><a class="nav-link" href="#inout" data-toggle="tab">IN-OUT</a></li>-->

                <!--<li class="nav-item"><a class="nav-link" href="#Timeline" data-toggle="tab">IN-OUT</a></li>-->
            </ul>
        </div><!-- /.card-header -->
        <div class="card-body">
            <div class="tab-content">
                <div class="active tab-pane" id="additionalinfo">
                    <?php Pjax::begin(); ?>

                    <?=
                    GridView::widget([
                        'dataProvider' => $dataProvider,
                        'filterModel' => $searchModel,
                        'responsive' => true,
                        'pageSummaryContainer' => ['style' => 'bottom: 50px'],
                        'resizableColumns' => true,
                        'hover' => true,
                        'pjax' => true,
                        'pjaxSettings' => [
                            'neverTimeout' => true,
//                    'beforeGrid' => 'My fancy content before.',
//                    'afterGrid' => 'My fancy content after.',
                        ],
                        'panel' => [
                            'type' => 'primary ',
                            'before' => Html::button('<i class="fas fa-print"></i> PRINT', ['class' => 'btn btn-default', 'id' => 'memberledger']),
                            'heading' => $counterData['name'] . '-' . $counterData['code'] . ' is Your Current Counter.',
                        ],
                        'toolbar' => ['{toggleData}{export}'],
                        'export' => [
                            'showConfirmAlert' => true,
                            'target' => GridView::TARGET_BLANK,
                        ],
                        'exportConfig' => [
                            GridView::CSV => [
                                'filename' => 'member data',
                            ],
                            GridView::EXCEL => [
                                'filename' => 'member data',
                            ],
                            GridView::PDF => [
                                'filename' => 'member data',
                                'options' => [
                                    'title' => 'Title',
                                    'subject' => Yii::t('app', 'PDF export generated by kartik-v/yii2-grid extension'),
                                    'keywords' => Yii::t('app', 'krajee, grid, export, yii2-grid, pdf')
                                ],
                                'contentBefore' => 'Content Before',
                                'contentAfter' => 'Con After'
                            ],
                        ],
                        'options' => ['id' => 'griditems'],
                        'columns' => [
                            ['class' => 'yii\grid\SerialColumn',
                                'headerOptions' => ['style' => 'width:3%']
                            ],
                        
                            ['attribute' => 'card_no',
                                'headerOptions' => ['style' => 'width:10%']
                            ],
                            ['attribute' => 'name',
                                'headerOptions' => ['style' => 'width:40%']
                            ],
                            [
                                'attribute' => 'Current Points',
                                'label' => 'POINTS',
                                'headerOptions' => ['style' => 'width:8%'],
                                'value' => function ($data) {
                                    $helper = new backend\controllers\Helper();
                                    $totalCr = \backend\models\Points::find()->where(['fk_member' => $data->id])->andWhere(['fk_org' => $helper->getActiveOrganization()])->andWhere(['points_action' => 0])->sum('points');
                                    $totalDR = \backend\models\Points::find()->where(['fk_member' => $data->id])->andWhere(['fk_org' => $helper->getActiveOrganization()])->andWhere(['points_action' => 1])->sum('points');

                                    // $inout = \backend\models\Transactions::find()->where(['fk_member'=>$id])->limit(10)->all();
                                    $points = abs($totalCr) - abs($totalDR);
                                    return $points;
                                }
                            ],
                            //'idendity_no',
//                    ['attribute' => 'idendity_no',
//                        'headerOptions' => ['style' => 'width:19%']
//                    ],
                            [
                                'attribute' => 'Action Button',
                                'format' => 'raw',
                                'value' => function ($model, $key, $index, $column) use ($counterNo) {
//                            var_dump($counterNo);
//                            die;

                                    return Html::a(
                                            Yii::t('app', '<i class="fa fa-plus">CR</i>'),
                                            ['points/create', 'id' => $model->id, 'cno' => $counterNo, 't' => 0],
                                            ['class' => 'btn btn-default btn-sm m-1', 'title' => 'CREDIT'],
                                    ) . Html::a(
                                            Yii::t('app', '<i class="fa fa-minus">DR</i>'),
                                            ['points/create', 'id' => $model->id, 'cno' => $counterNo, 't' => 1],
                                            ['class' => 'btn btn-default btn-sm m-1', 'title' => 'DEBIT'],
                                    ) . Html::a(
                                            Yii::t('app', '<i class="fa fa-eye">view</i>'),
                                            ['ac/member-details', 'm' => $model->id, 'c' => $counterNo],
                                            ['class' => 'btn btn-default btn-sm m-1', 'title' => 'DETAILS'],
                                    );
                                },
                                'headerOptions' => ['style' => 'width:20%']
                            ],
                            [
                                'class' => '\kartik\grid\CheckboxColumn',
                                'width' => '1%',
                                'checkboxOptions' => function ($model) {
                                    return [
                                'value' => $model->id,
                                    ];
                                },
//                         'headerOptions' => ['style' => 'width:4%'],
                            ],
                        ]
                    ]);
                    ?>


<?php Pjax::end(); ?>
                </div>


                <div class=" tab-pane" id="counterReport">
<?php Pjax::begin(); ?>

                    <?=
                    GridView::widget([
                        'dataProvider' => $dataProviderPoints,
//                        'filterModel' => $searchModelPoints,
                        'responsive' => true,
//                    'options' => ['style' => 'font-size:12px;'],
                        'resizableColumns' => true,
                        'hover' => true,
                        'pjax' => true,
                        'pjaxSettings' => [
                            'neverTimeout' => true,
//                    'beforeGrid' => 'My fancy content before.',
//                    'afterGrid' => 'My fancy content after.',
                        ],
                        'panel' => [
                            'type' => 'primary ',
//                            'before' => Html::button('<i class="fa far fa-print"></i> Privacy Statement', [
//                                'class' => 'btn btn-primary',
//                                'id'=>'counterReport',
//                                'target' => '_blank',
//                                'data-toggle' => 'tooltip',
//                                'title' => 'Will open the generated PDF file in a new window'
//                            ]),
                            'heading' => $counterData['name'] . '-' . $counterData['code'] . ' is Your Current Counter.',
                        ],
                        'showPageSummary' => false,
                        'toolbar' => ['{toggleData}{export}'],
                        'export' => [
                            'showConfirmAlert' => true,
                            'target' => GridView::TARGET_BLANK,
                        ],
                        'exportConfig' => [
                            GridView::CSV => [
                                'filename' => 'member data',
                            ],
                            GridView::EXCEL => [
                                'filename' => 'member data',
                            ],
                            GridView::PDF => [
                                'filename' => 'member data',
                            ],
                        ],
                        'options' => ['id' => 'griditems'],
                        'columns' => [
                            ['class' => 'yii\grid\SerialColumn'],
                            [
                                'attribute' => 'points_action',
                                'label' => 'Action',
                                'value' => function ($data) {
                                    if ($data['points_action'] == 1) {
                                        return "DEBIT";
                                    } else {
                                        return "CREDIT";
                                    }
                                },
                                'filter' => ['1' => 'DEBIT', '0' => 'CREDIT'],
                                'filterType' => GridView::FILTER_SELECT2,
                                'filterWidgetOptions' => [
                                    'options' => ['prompt' => 'All', 'class' => 'text-xs'],
                                    'pluginOptions' => ['allowClear' => true],
                                ],
                                'headerOptions' => ['style' => 'width:10%']
                            ],
                            [
                                'attribute' => 'net_points',
                                'label' => 'Type',
                                'filter' => ['POINTS' => 'POINTS', 'CASH' => 'CASH'],
                                'filterType' => GridView::FILTER_SELECT2,
                                'filterWidgetOptions' => [
                                    'options' => ['prompt' => 'All', 'class' => 'text-xs'],
                                    'pluginOptions' => ['allowClear' => true],
                                ],
                                'headerOptions' => ['style' => 'width:10%']
                            ],
                            [
                                'attribute' => 'fk_member',
                                'label' => 'Member',
                                'value' => function ($data) {

                                    $member_name = \backend\models\Members::findOne(['id' => $data->fk_member]);
                                    return $member_name['name'] . '-' . $member_name['card_no'];
                                },
                                'filter' => ArrayHelper::map(\backend\models\Members::find()->where(['fk_org' => $helper->getActiveOrganization()])->all(), 'id', 'name'),
                                'filterType' => GridView::FILTER_SELECT2,
                                'filterWidgetOptions' => [
                                    'options' => ['prompt' => 'All', 'class' => 'text-xs'],
                                    'pluginOptions' => ['allowClear' => true],
                                ],
                                'headerOptions' => ['style' => 'width:32%']
                            ],
                            ['attribute' => 'points',
                                'headerOptions' => ['style' => 'width:6%']
                            ],
                            // 'date',
                            'time:datetime',
                            [
                                'attribute' => 'fk_user',
                                'label' => 'Entry By',
                                'value' => function ($data) {
                                    $user_name = \backend\models\User::findOne(['id' => $data->fk_user]);
                                    return $user_name['username'];
                                }
                            ],
//                            [
//                                'class' => '\kartik\grid\CheckboxColumn',
//                                'width' => '1%',
//                                'checkboxOptions' => function ($model) {
//                                    return [
//                                'value' => $model->id,
//                                    ];
//                                },
////                         'headerOptions' => ['style' => 'width:4%'],
//                            ],
                        ],
                    ]);
                    ?>


<?php Pjax::end(); ?>
                </div>
            </div>
            <!-- /.tab-content -->
        </div><!-- /.card-body -->

        <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->